### ISSUE TITLE
Give the real credit

### ISSUE THREAD

**Issue by randock233** [HoldUpAMinute/mInventory#2]
We both know you didnt make this, Please give the credit to ChatGPT.

**Comment by HoldUpAMinute** [comment]
Hello! Randock please stop attempting to make false accusations until you can provide proof.

**Comment by randock233** [comment]
This is not his work, He used ChatGPT to make this

**Comment by HoldUpAMinute** [comment]
I've reported this harassment. Please stop.

**Comment by randock233** [comment]
> I've reported this harassment. Please stop.

I have proof of  you using chatgt.

**Comment by HoldUpAMinute** [comment]
I've reported this harassment. Please stop.
